from __future__ import annotations

import argparse
import csv
import json
from collections import Counter, defaultdict
from dataclasses import asdict, dataclass
from pathlib import Path


DEFAULT_ACTION_IDS = [
    "c106",
    "c019",
    "c015",
    "c016",
    "c156",
    "c151",
    "c154",
    "c059",
    "c097",
    "c150",
    "c052",
    "c051",
    "c147",
    "c107",
    "c110",
    "c109",
    "c065",
    "c123",
    "c125",
    "c132",
]


@dataclass(frozen=True)
class CharadesSubsetRow:
    video_id: str
    subject: str
    scene: str
    quality: int
    relevance: int
    verified: str
    video_length: float
    action_id: str
    action_index: int
    action: str
    action_name: str
    object_id: str
    object_name: str
    verb_id: str
    verb_name: str
    start_seconds: float
    end_seconds: float
    duration_seconds: float
    clip_start_seconds: float
    clip_end_seconds: float
    clip_duration_seconds: float
    objects: str
    descriptions: str


def main() -> None:
    parser = argparse.ArgumentParser(description="Build a balanced Charades pilot subset from a prepared action manifest.")
    parser.add_argument("manifest", type=Path, help="Charades action manifest generated by prepare_charades.py.")
    parser.add_argument("--actions", nargs="+", default=DEFAULT_ACTION_IDS, help="Action IDs to sample, e.g. c106 106 c019.")
    parser.add_argument("--max-videos", type=int, default=50, help="Maximum selected unique videos.")
    parser.add_argument("--samples-per-action", type=int, default=4, help="Maximum selected videos per action.")
    parser.add_argument("--max-per-scene", type=int, default=8, help="Maximum selected videos per scene.")
    parser.add_argument("--min-duration", type=float, default=2.0, help="Minimum action duration in seconds.")
    parser.add_argument("--context-seconds", type=float, default=2.0, help="Seconds to include before and after the action window.")
    parser.add_argument("--output", type=Path, default=Path("data/charades/charades_pilot_subset.csv"))
    parser.add_argument("--json-output", type=Path, default=Path("data/charades/charades_pilot_subset.json"))
    parser.add_argument("--summary-output", type=Path, default=Path("data/charades/charades_pilot_subset_summary.json"))
    args = parser.parse_args()

    rows = build_subset(
        manifest_path=args.manifest,
        action_ids=[normalize_action_id(item) for item in args.actions],
        max_videos=args.max_videos,
        samples_per_action=args.samples_per_action,
        max_per_scene=args.max_per_scene,
        min_duration=args.min_duration,
        context_seconds=args.context_seconds,
    )
    args.output.parent.mkdir(parents=True, exist_ok=True)
    write_csv(args.output, rows)
    args.json_output.write_text(json.dumps([asdict(row) for row in rows], ensure_ascii=False, indent=2), encoding="utf-8")
    args.summary_output.write_text(json.dumps(build_summary(rows), ensure_ascii=False, indent=2), encoding="utf-8")

    print(f"wrote {len(rows)} selected videos to {args.output}")
    print(f"wrote summary to {args.summary_output}")


def build_subset(
    manifest_path: Path,
    action_ids: list[str],
    max_videos: int,
    samples_per_action: int,
    max_per_scene: int,
    min_duration: float,
    context_seconds: float,
) -> list[CharadesSubsetRow]:
    if not manifest_path.exists():
        raise FileNotFoundError(f"Charades manifest does not exist: {manifest_path}")

    candidates_by_action: dict[str, list[CharadesSubsetRow]] = defaultdict(list)
    action_id_set = set(action_ids)
    with manifest_path.open("r", encoding="utf-8", newline="") as file:
        reader = csv.DictReader(file)
        for record in reader:
            action_id = normalize_action_id(record["action_id"])
            duration = float(record["duration_seconds"])
            if action_id not in action_id_set or duration < min_duration:
                continue
            candidates_by_action[action_id].append(to_subset_row(record, context_seconds))

    for candidates in candidates_by_action.values():
        candidates.sort(
            key=lambda row: (
                -row.quality,
                -row.relevance,
                -row.duration_seconds,
                row.video_id,
                row.start_seconds,
            )
        )

    selected: list[CharadesSubsetRow] = []
    used_videos: set[str] = set()
    action_counts: Counter[str] = Counter()
    scene_counts: Counter[str] = Counter()
    indexes: dict[str, int] = defaultdict(int)

    while len(selected) < max_videos:
        added_in_round = False
        for action_id in action_ids:
            if len(selected) >= max_videos:
                break
            if action_counts[action_id] >= samples_per_action:
                continue

            candidates = candidates_by_action.get(action_id, [])
            while indexes[action_id] < len(candidates):
                candidate = candidates[indexes[action_id]]
                indexes[action_id] += 1
                if candidate.video_id in used_videos:
                    continue
                if scene_counts[candidate.scene] >= max_per_scene:
                    continue
                selected.append(candidate)
                used_videos.add(candidate.video_id)
                action_counts[action_id] += 1
                scene_counts[candidate.scene] += 1
                added_in_round = True
                break

        if not added_in_round:
            break

    return selected


def to_subset_row(record: dict[str, str], context_seconds: float) -> CharadesSubsetRow:
    video_length = float(record["video_length"])
    start_seconds = float(record["start_seconds"])
    end_seconds = float(record["end_seconds"])
    clip_start_seconds = max(0.0, start_seconds - context_seconds)
    clip_end_seconds = min(video_length, end_seconds + context_seconds)
    return CharadesSubsetRow(
        video_id=record["video_id"],
        subject=record["subject"],
        scene=record["scene"],
        quality=parse_int(record["quality"]),
        relevance=parse_int(record["relevance"]),
        verified=record["verified"],
        video_length=round(video_length, 4),
        action_id=normalize_action_id(record["action_id"]),
        action_index=int(record["action_index"]),
        action=record["action"],
        action_name=record["action_name"],
        object_id=record["object_id"],
        object_name=record["object_name"],
        verb_id=record["verb_id"],
        verb_name=record["verb_name"],
        start_seconds=round(start_seconds, 4),
        end_seconds=round(end_seconds, 4),
        duration_seconds=round(float(record["duration_seconds"]), 4),
        clip_start_seconds=round(clip_start_seconds, 4),
        clip_end_seconds=round(clip_end_seconds, 4),
        clip_duration_seconds=round(max(0.0, clip_end_seconds - clip_start_seconds), 4),
        objects=record["objects"],
        descriptions=record["descriptions"],
    )


def build_summary(rows: list[CharadesSubsetRow]) -> dict[str, object]:
    return {
        "selected_videos": len({row.video_id for row in rows}),
        "selected_rows": len(rows),
        "actions": len({row.action_id for row in rows}),
        "scenes": len({row.scene for row in rows}),
        "average_clip_duration_seconds": round(sum(row.clip_duration_seconds for row in rows) / len(rows), 4) if rows else 0.0,
        "by_action": [
            {
                "action_id": action_id,
                "action_name": action_name,
                "count": count,
            }
            for (action_id, action_name), count in sorted(Counter((row.action_id, row.action_name) for row in rows).items())
        ],
        "by_scene": dict(Counter(row.scene for row in rows).most_common()),
        "video_ids": [row.video_id for row in rows],
    }


def normalize_action_id(value: str) -> str:
    value = value.strip()
    if value.startswith("c"):
        return f"c{int(value[1:]):03d}"
    return f"c{int(value):03d}"


def parse_int(value: str) -> int:
    if value == "":
        return 0
    return int(float(value))


def write_csv(path: Path, rows: list[CharadesSubsetRow]) -> None:
    fieldnames = [
        "video_id",
        "subject",
        "scene",
        "quality",
        "relevance",
        "verified",
        "video_length",
        "action_id",
        "action_index",
        "action",
        "action_name",
        "object_id",
        "object_name",
        "verb_id",
        "verb_name",
        "start_seconds",
        "end_seconds",
        "duration_seconds",
        "clip_start_seconds",
        "clip_end_seconds",
        "clip_duration_seconds",
        "objects",
        "descriptions",
    ]
    with path.open("w", encoding="utf-8", newline="") as file:
        writer = csv.DictWriter(file, fieldnames=fieldnames)
        writer.writeheader()
        for row in rows:
            writer.writerow(asdict(row))


if __name__ == "__main__":
    main()
