"""Smoke-test Charades TAL annotations with cached features.

This validates the contract that ActionFormer-style data loading needs:

  clips manifest + TAL annotations + feature manifest + .npz feats
      -> data_dict with feats C x T, segments N x 2 in feature grid, labels N

It intentionally does not import the official ActionFormer dataset registry yet.
The goal is to validate our Charades clip-level feature cache and annotation
alignment before adding a full `charades.py` dataset adapter under the external
ActionFormer tree.
"""
from __future__ import annotations

import argparse
import csv
import json
import sys
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any

import numpy as np


PROJECT_ROOT = Path(__file__).resolve().parents[2]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))


@dataclass(frozen=True)
class DataLoaderSmokeRecord:
    clip_id: str
    video_id: str
    feature_path: str
    status: str
    feats_shape: list[int]
    segments_shape: list[int]
    labels_shape: list[int]
    source_fps: float
    feature_fps: float
    feat_stride: float
    feat_num_frames: int
    clip_start_seconds: float
    clip_end_seconds: float
    local_segments_seconds: list[list[float]]
    grid_segments: list[list[float]]
    labels: list[int]
    error: str = ""


def main() -> None:
    parser = argparse.ArgumentParser(description="Smoke-test ActionFormer data dict loading for Charades clips.")
    parser.add_argument("clips_manifest", type=Path, help="Clips CSV generated by slice_charades_clips.py.")
    parser.add_argument(
        "--annotations",
        type=Path,
        default=Path("data/charades/tal_annotations.json"),
        help="ActionFormer-format Charades annotations JSON.",
    )
    parser.add_argument(
        "--feature-manifest",
        type=Path,
        default=Path("data/charades/features_smoke_manifest.json"),
        help="Feature cache manifest JSON generated by extract_slowfast_features.py.",
    )
    parser.add_argument(
        "--summary-output",
        type=Path,
        default=Path("outputs/tal_dataloader_smoke_summary.json"),
        help="Output summary JSON path.",
    )
    parser.add_argument("--feat-num-frames", type=int, default=1, help="Feature extractor temporal receptive field in frames.")
    parser.add_argument("--downsample-rate", type=int, default=1, help="Feature downsample rate used by ActionFormer loader.")
    parser.add_argument("--limit", type=int, default=None, help="Maximum clips to validate.")
    parser.add_argument("--offset", type=int, default=0, help="Skip first N eligible clips.")
    args = parser.parse_args()

    records = smoke_load_manifest(
        clips_manifest=args.clips_manifest,
        annotations_path=args.annotations,
        feature_manifest_path=args.feature_manifest,
        feat_num_frames=args.feat_num_frames,
        downsample_rate=args.downsample_rate,
        offset=args.offset,
        limit=args.limit,
    )
    payload = {"summary": build_summary(records), "records": [asdict(record) for record in records]}
    args.summary_output.parent.mkdir(parents=True, exist_ok=True)
    args.summary_output.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")
    print(json.dumps(payload["summary"], ensure_ascii=False, indent=2))
    print(f"wrote {args.summary_output}")


def smoke_load_manifest(
    *,
    clips_manifest: Path,
    annotations_path: Path,
    feature_manifest_path: Path,
    feat_num_frames: int,
    downsample_rate: int,
    offset: int,
    limit: int | None,
) -> list[DataLoaderSmokeRecord]:
    rows = read_clip_rows(clips_manifest, offset=offset, limit=limit)
    annotations = json.loads(annotations_path.read_text(encoding="utf-8"))
    feature_manifest = json.loads(feature_manifest_path.read_text(encoding="utf-8"))
    feature_db = feature_manifest.get("database", {})
    records: list[DataLoaderSmokeRecord] = []
    for row in rows:
        records.append(
            smoke_load_clip(
                row=row,
                annotation_db=annotations.get("database", {}),
                feature_db=feature_db,
                feat_num_frames=feat_num_frames,
                downsample_rate=downsample_rate,
            )
        )
    return records


def smoke_load_clip(
    *,
    row: dict[str, str],
    annotation_db: dict[str, Any],
    feature_db: dict[str, Any],
    feat_num_frames: int,
    downsample_rate: int,
) -> DataLoaderSmokeRecord:
    clip_id = row["clip_id"]
    video_id = row["video_id"]
    clip_start = float(row.get("clip_start_seconds", 0.0) or 0.0)
    clip_end = float(row.get("clip_end_seconds", 0.0) or 0.0)
    feature_entry = feature_db.get(clip_id)
    if feature_entry is None:
        return make_record(row, "", "missing_feature_entry", [0, 0], [], [], 0.0, 0.0, 0.0, feat_num_frames, [])

    feature_path = feature_entry.get("feature_path", "")
    try:
        with np.load(feature_path) as data:
            feats_txc = data["feats"].astype(np.float32)
    except Exception as exc:
        return make_record(row, feature_path, "feature_load_failed", [0, 0], [], [], 0.0, 0.0, 0.0, feat_num_frames, [], str(exc))

    source_fps = float(feature_entry.get("source_fps") or 0.0)
    feature_fps = float(feature_entry.get("feature_fps") or 0.0)
    if source_fps <= 0 or feature_fps <= 0:
        return make_record(row, feature_path, "invalid_feature_meta", list(feats_txc.T.shape), [], [], source_fps, feature_fps, 0.0, feat_num_frames, [])
    if downsample_rate <= 0:
        return make_record(row, feature_path, "invalid_downsample_rate", list(feats_txc.T.shape), [], [], source_fps, feature_fps, 0.0, feat_num_frames, [])

    feats_txc = feats_txc[::downsample_rate, :]
    feats_cxt = np.ascontiguousarray(feats_txc.transpose())
    feat_stride = (source_fps / feature_fps) * downsample_rate
    feat_offset = 0.5 * feat_num_frames / feat_stride

    local_segments, labels = intersect_clip_annotations(
        annotation_db.get(video_id, {}).get("annotations", []),
        clip_start=clip_start,
        clip_end=clip_end,
    )
    grid_segments = seconds_to_feature_grid(
        local_segments,
        source_fps=source_fps,
        feat_stride=feat_stride,
        feat_offset=feat_offset,
    )

    status = "ok"
    if not labels:
        status = "no_intersecting_annotations"
    elif len(feats_cxt.shape) != 2 or feats_cxt.shape[1] == 0:
        status = "empty_features"
    elif not segments_fit_feature_length(grid_segments, feats_cxt.shape[1]):
        status = "segments_outside_feature_grid"

    return make_record(
        row,
        feature_path,
        status,
        list(feats_cxt.shape),
        local_segments,
        grid_segments,
        source_fps,
        feature_fps,
        feat_stride,
        feat_num_frames,
        labels,
    )


def intersect_clip_annotations(
    annotations: list[dict[str, Any]],
    *,
    clip_start: float,
    clip_end: float,
) -> tuple[list[list[float]], list[int]]:
    local_segments: list[list[float]] = []
    labels: list[int] = []
    for annotation in annotations:
        start, end = annotation.get("segment", [0.0, 0.0])
        left = max(float(start), clip_start)
        right = min(float(end), clip_end)
        if right <= left:
            continue
        local_segments.append([round(left - clip_start, 4), round(right - clip_start, 4)])
        labels.append(int(annotation["label_id"]))
    return local_segments, labels


def seconds_to_feature_grid(
    local_segments: list[list[float]],
    *,
    source_fps: float,
    feat_stride: float,
    feat_offset: float,
) -> list[list[float]]:
    return [
        [
            round(segment[0] * source_fps / feat_stride - feat_offset, 4),
            round(segment[1] * source_fps / feat_stride - feat_offset, 4),
        ]
        for segment in local_segments
    ]


def segments_fit_feature_length(grid_segments: list[list[float]], feature_length: int) -> bool:
    if not grid_segments:
        return True
    for start, end in grid_segments:
        if end <= start:
            return False
        if end < -1.0 or start > feature_length + 1.0:
            return False
    return True


def read_clip_rows(path: Path, offset: int, limit: int | None) -> list[dict[str, str]]:
    rows: list[dict[str, str]] = []
    with path.open("r", encoding="utf-8", newline="") as file:
        reader = csv.DictReader(file)
        for index, row in enumerate(reader):
            if row.get("status") not in {"sliced", "exists"}:
                continue
            if index < offset:
                continue
            rows.append(row)
            if limit is not None and len(rows) >= limit:
                break
    return rows


def make_record(
    row: dict[str, str],
    feature_path: str,
    status: str,
    feats_shape: list[int],
    local_segments: list[list[float]],
    grid_segments: list[list[float]],
    source_fps: float,
    feature_fps: float,
    feat_stride: float,
    feat_num_frames: int,
    labels: list[int],
    error: str = "",
) -> DataLoaderSmokeRecord:
    return DataLoaderSmokeRecord(
        clip_id=row.get("clip_id", ""),
        video_id=row.get("video_id", ""),
        feature_path=feature_path,
        status=status,
        feats_shape=[int(value) for value in feats_shape],
        segments_shape=[len(grid_segments), 2] if grid_segments else [0, 2],
        labels_shape=[len(labels)],
        source_fps=round(float(source_fps), 4),
        feature_fps=round(float(feature_fps), 4),
        feat_stride=round(float(feat_stride), 4),
        feat_num_frames=int(feat_num_frames),
        clip_start_seconds=round(float(row.get("clip_start_seconds", 0.0) or 0.0), 4),
        clip_end_seconds=round(float(row.get("clip_end_seconds", 0.0) or 0.0), 4),
        local_segments_seconds=local_segments,
        grid_segments=grid_segments,
        labels=labels,
        error=error,
    )


def build_summary(records: list[DataLoaderSmokeRecord]) -> dict[str, object]:
    status_counts: dict[str, int] = {}
    for record in records:
        status_counts[record.status] = status_counts.get(record.status, 0) + 1
    feature_dims = sorted({record.feats_shape[0] for record in records if len(record.feats_shape) == 2 and record.feats_shape[0] > 0})
    feature_lengths = [record.feats_shape[1] for record in records if len(record.feats_shape) == 2 and record.feats_shape[1] > 0]
    total_segments = sum(record.labels_shape[0] for record in records)
    return {
        "total": len(records),
        "status_counts": status_counts,
        "feature_dims_c": feature_dims,
        "min_feature_length_t": min(feature_lengths) if feature_lengths else 0,
        "max_feature_length_t": max(feature_lengths) if feature_lengths else 0,
        "total_segments": total_segments,
    }


if __name__ == "__main__":
    main()
