"""Extract ActionFormer-compatible feature cache for Charades clips.

The default backend is `cv2-smoke`: it does not run a real SlowFast network.
Instead, it samples frames, resizes each frame to 32x24 RGB, flattens it to
2304 dimensions, and writes an `.npz` file with a `feats` array shaped T x C.

This gives us a fast local contract test for:
  mp4 -> feature tensor -> .npz -> ActionFormer-compatible cache manifest

On the GPU machine, this script is the integration point for replacing
`cv2-smoke` with real SlowFast R50 features while keeping the same output
schema. The SlowFast backend is optional and intended for Linux GPU machines
with pytorchvideo installed.
"""
from __future__ import annotations

import argparse
import csv
import json
import sys
from dataclasses import asdict, dataclass
from pathlib import Path

import cv2
import numpy as np


PROJECT_ROOT = Path(__file__).resolve().parents[2]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))


SMOKE_FRAME_SIZE = (32, 24)  # width, height; 32 * 24 * 3 = 2304.
SLOWFAST_MEAN = np.asarray([0.45, 0.45, 0.45], dtype=np.float32)
SLOWFAST_STD = np.asarray([0.225, 0.225, 0.225], dtype=np.float32)


@dataclass(frozen=True)
class FeatureRecord:
    clip_id: str
    video_id: str
    action_id: str
    clip_path: str
    feature_path: str
    status: str
    backend: str
    num_frames: int
    source_fps: float
    duration_seconds: float
    feature_fps: float
    feature_shape: list[int]
    error: str = ""


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Extract ActionFormer-compatible features for Charades clips."
    )
    parser.add_argument(
        "clips_manifest",
        type=Path,
        help="Clips CSV generated by slice_charades_clips.py.",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("data/charades/features_smoke"),
        help="Directory for .npz feature files.",
    )
    parser.add_argument(
        "--summary-output",
        type=Path,
        default=Path("outputs/tal_features_smoke_summary.json"),
        help="Summary JSON output path.",
    )
    parser.add_argument(
        "--feature-manifest-output",
        type=Path,
        default=Path("data/charades/features_smoke_manifest.json"),
        help="Feature cache manifest JSON output path.",
    )
    parser.add_argument(
        "--backend",
        choices=["cv2-smoke", "slowfast-r50"],
        default="cv2-smoke",
        help="Feature backend. cv2-smoke is a local contract-test backend; slowfast-r50 requires pytorchvideo/torch.",
    )
    parser.add_argument("--sample-fps", type=float, default=2.0, help="Frames sampled per second.")
    parser.add_argument("--max-frames", type=int, default=256, help="Maximum sampled frames per clip.")
    parser.add_argument(
        "--device",
        choices=["auto", "cuda", "cpu", "mps"],
        default="auto",
        help="Device for slowfast-r50 backend.",
    )
    parser.add_argument("--slowfast-clip-frames", type=int, default=32, help="Frames per SlowFast window.")
    parser.add_argument("--slowfast-alpha", type=int, default=4, help="Slow pathway temporal sampling factor.")
    parser.add_argument("--slowfast-crop-size", type=int, default=256, help="Square crop/resize size for SlowFast input.")
    parser.add_argument("--limit", type=int, default=None, help="Maximum clips to process.")
    parser.add_argument("--offset", type=int, default=0, help="Skip first N eligible clips.")
    parser.add_argument("--overwrite", action="store_true", help="Overwrite existing feature files.")
    args = parser.parse_args()

    records = extract_features_for_manifest(
        clips_manifest=args.clips_manifest,
        output_dir=args.output_dir,
        backend=args.backend,
        sample_fps=args.sample_fps,
        max_frames=args.max_frames,
        device=args.device,
        slowfast_clip_frames=args.slowfast_clip_frames,
        slowfast_alpha=args.slowfast_alpha,
        slowfast_crop_size=args.slowfast_crop_size,
        offset=args.offset,
        limit=args.limit,
        overwrite=args.overwrite,
    )

    args.summary_output.parent.mkdir(parents=True, exist_ok=True)
    args.feature_manifest_output.parent.mkdir(parents=True, exist_ok=True)
    args.summary_output.write_text(
        json.dumps({"summary": build_summary(records), "records": [asdict(record) for record in records]}, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    args.feature_manifest_output.write_text(
        json.dumps(build_feature_manifest(records), ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    print(json.dumps(build_summary(records), ensure_ascii=False, indent=2))
    print(f"wrote {args.summary_output}")
    print(f"wrote {args.feature_manifest_output}")


def extract_features_for_manifest(
    *,
    clips_manifest: Path,
    output_dir: Path,
    backend: str,
    sample_fps: float,
    max_frames: int,
    device: str = "auto",
    slowfast_clip_frames: int = 32,
    slowfast_alpha: int = 4,
    slowfast_crop_size: int = 256,
    offset: int,
    limit: int | None,
    overwrite: bool,
) -> list[FeatureRecord]:
    if backend not in {"cv2-smoke", "slowfast-r50"}:
        raise ValueError(f"Unsupported backend: {backend}")
    rows = read_clip_rows(clips_manifest, offset=offset, limit=limit)
    output_dir.mkdir(parents=True, exist_ok=True)
    records: list[FeatureRecord] = []
    slowfast_extractor = None
    if backend == "slowfast-r50":
        slowfast_extractor = SlowFastR50Extractor(
            device=device,
            clip_frames=slowfast_clip_frames,
            alpha=slowfast_alpha,
            crop_size=slowfast_crop_size,
        )
    for row in rows:
        records.append(
            extract_one_clip(
                row=row,
                output_dir=output_dir,
                backend=backend,
                sample_fps=sample_fps,
                max_frames=max_frames,
                slowfast_extractor=slowfast_extractor,
                overwrite=overwrite,
            )
        )
    return records


def extract_one_clip(
    *,
    row: dict[str, str],
    output_dir: Path,
    backend: str,
    sample_fps: float,
    max_frames: int,
    slowfast_extractor: "SlowFastR50Extractor | None" = None,
    overwrite: bool,
) -> FeatureRecord:
    clip_id = row["clip_id"]
    clip_path = Path(row["clip_path"])
    feature_path = output_dir / f"{clip_id}.npz"
    if feature_path.exists() and not overwrite:
        try:
            with np.load(feature_path) as data:
                shape = list(data["feats"].shape)
                source_fps = float(data.get("source_fps", 0.0))
                duration = float(data.get("duration_seconds", 0.0))
                feature_fps = float(data.get("feature_fps", sample_fps))
            return make_record(row, feature_path, "exists", backend, shape, source_fps, duration, feature_fps)
        except Exception:
            pass

    if not clip_path.exists():
        return make_record(row, feature_path, "missing_source", backend, [0, 0], 0.0, 0.0, sample_fps, f"Missing clip: {clip_path}")

    try:
        if backend == "cv2-smoke":
            feats, meta = extract_cv2_smoke_features(clip_path, sample_fps=sample_fps, max_frames=max_frames)
        elif backend == "slowfast-r50":
            if slowfast_extractor is None:
                raise ValueError("slowfast-r50 backend requires a SlowFastR50Extractor")
            feats, meta = slowfast_extractor.extract(clip_path, sample_fps=sample_fps, max_frames=max_frames)
        else:
            raise ValueError(f"Unsupported backend: {backend}")
        np.savez_compressed(
            feature_path,
            feats=feats.astype(np.float32),
            clip_id=clip_id,
            video_id=row.get("video_id", ""),
            action_id=row.get("action_id", ""),
            backend=backend,
            source_fps=np.float32(meta["source_fps"]),
            duration_seconds=np.float32(meta["duration_seconds"]),
            feature_fps=np.float32(meta["feature_fps"]),
            frame_indices=np.asarray(meta["frame_indices"], dtype=np.int32),
        )
        return make_record(
            row,
            feature_path,
            "extracted",
            backend,
            list(feats.shape),
            meta["source_fps"],
            meta["duration_seconds"],
            meta["feature_fps"],
        )
    except Exception as exc:
        return make_record(row, feature_path, "failed", backend, [0, 0], 0.0, 0.0, sample_fps, str(exc))


def extract_cv2_smoke_features(video_path: Path, sample_fps: float, max_frames: int) -> tuple[np.ndarray, dict[str, object]]:
    capture = cv2.VideoCapture(str(video_path))
    if not capture.isOpened():
        raise ValueError(f"Could not open video: {video_path}")
    try:
        source_fps = float(capture.get(cv2.CAP_PROP_FPS) or 0.0)
        frame_count = int(capture.get(cv2.CAP_PROP_FRAME_COUNT) or 0)
        if source_fps <= 0 or frame_count <= 0:
            raise ValueError(f"Invalid video metadata: fps={source_fps}, frames={frame_count}")
        duration = frame_count / source_fps
        indices = sample_frame_indices(frame_count=frame_count, source_fps=source_fps, sample_fps=sample_fps, max_frames=max_frames)
        features = []
        for index in indices:
            capture.set(cv2.CAP_PROP_POS_FRAMES, int(index))
            ok, frame_bgr = capture.read()
            if not ok or frame_bgr is None:
                continue
            features.append(frame_to_smoke_feature(frame_bgr))
    finally:
        capture.release()

    if not features:
        raise ValueError(f"No frames could be decoded from {video_path}")
    feats = np.stack(features, axis=0).astype(np.float32)
    return feats, {
        "source_fps": source_fps,
        "duration_seconds": duration,
        "feature_fps": sample_fps,
        "frame_indices": indices,
    }


def frame_to_smoke_feature(frame_bgr: np.ndarray) -> np.ndarray:
    frame_rgb = cv2.cvtColor(frame_bgr, cv2.COLOR_BGR2RGB)
    resized = cv2.resize(frame_rgb, SMOKE_FRAME_SIZE, interpolation=cv2.INTER_AREA)
    return (resized.astype(np.float32) / 255.0).reshape(-1)


class SlowFastR50Extractor:
    """Extract pooled 2304-D SlowFast R50 features with pytorchvideo.

    The feature vector is captured before the final classification projection.
    Each sampled center frame produces one temporal feature, so the saved cache
    remains T x C and can be consumed by the Charades ActionFormer adapter.
    """

    def __init__(self, device: str, clip_frames: int, alpha: int, crop_size: int):
        if clip_frames <= 0:
            raise ValueError("slowfast clip_frames must be positive")
        if alpha <= 0:
            raise ValueError("slowfast alpha must be positive")
        self.clip_frames = clip_frames
        self.alpha = alpha
        self.crop_size = crop_size
        self.device = choose_torch_device(device)
        self.model = load_slowfast_r50_model()
        self.model.eval().to(self.device)
        self._captured_feature = None
        self._hook = register_slowfast_feature_hook(self.model, self)

    def extract(self, video_path: Path, sample_fps: float, max_frames: int) -> tuple[np.ndarray, dict[str, object]]:
        frames_rgb, source_fps, duration = load_video_frames_rgb(video_path)
        center_indices = sample_frame_indices(
            frame_count=len(frames_rgb),
            source_fps=source_fps,
            sample_fps=sample_fps,
            max_frames=max_frames,
        )
        features = []
        import torch

        with torch.no_grad():
            for center_index in center_indices:
                window = make_centered_window(frames_rgb, center_index, self.clip_frames)
                features.append(self.extract_window_feature(window))

        feats = np.stack(features, axis=0).astype(np.float32)
        return feats, {
            "source_fps": source_fps,
            "duration_seconds": duration,
            "feature_fps": sample_fps,
            "frame_indices": center_indices,
        }

    def extract_window_feature(self, window_rgb: np.ndarray) -> np.ndarray:
        pathways = build_slowfast_pathways(
            window_rgb,
            alpha=self.alpha,
            crop_size=self.crop_size,
        )
        pathways = [pathway.unsqueeze(0).to(self.device) for pathway in pathways]
        self._captured_feature = None
        _ = self.model(pathways)
        if self._captured_feature is None:
            raise RuntimeError("SlowFast feature hook did not capture projection input")
        return flatten_slowfast_feature(self._captured_feature)


def choose_torch_device(requested: str):
    import torch

    if requested == "auto":
        if torch.cuda.is_available():
            return torch.device("cuda")
        if torch.backends.mps.is_available() and torch.backends.mps.is_built():
            return torch.device("mps")
        return torch.device("cpu")
    if requested == "cuda" and not torch.cuda.is_available():
        raise RuntimeError("CUDA requested but torch.cuda.is_available() is false")
    if requested == "mps" and not (torch.backends.mps.is_available() and torch.backends.mps.is_built()):
        raise RuntimeError("MPS requested but it is not available")
    return torch.device(requested)


def load_slowfast_r50_model():
    try:
        from pytorchvideo.models.hub import slowfast_r50

        return slowfast_r50(pretrained=True)
    except ImportError as exc:
        raise RuntimeError(
            "slowfast-r50 backend requires pytorchvideo. Install it on the GPU machine with: "
            "pip install pytorchvideo"
        ) from exc


def register_slowfast_feature_hook(model, extractor: SlowFastR50Extractor):
    head = getattr(model, "blocks", [None])[-1]
    projection = getattr(head, "proj", None)
    if projection is None:
        raise RuntimeError("Could not find SlowFast head projection layer for feature hook")

    def capture_projection_input(_module, inputs):
        feature = inputs[0]
        extractor._captured_feature = feature.detach()

    return projection.register_forward_pre_hook(capture_projection_input)


def load_video_frames_rgb(video_path: Path) -> tuple[np.ndarray, float, float]:
    capture = cv2.VideoCapture(str(video_path))
    if not capture.isOpened():
        raise ValueError(f"Could not open video: {video_path}")
    frames = []
    try:
        source_fps = float(capture.get(cv2.CAP_PROP_FPS) or 0.0)
        frame_count = int(capture.get(cv2.CAP_PROP_FRAME_COUNT) or 0)
        if source_fps <= 0 or frame_count <= 0:
            raise ValueError(f"Invalid video metadata: fps={source_fps}, frames={frame_count}")
        while True:
            ok, frame_bgr = capture.read()
            if not ok or frame_bgr is None:
                break
            frames.append(cv2.cvtColor(frame_bgr, cv2.COLOR_BGR2RGB))
    finally:
        capture.release()
    if not frames:
        raise ValueError(f"No frames could be decoded from {video_path}")
    return np.stack(frames, axis=0), source_fps, len(frames) / source_fps


def make_centered_window(frames_rgb: np.ndarray, center_index: int, clip_frames: int) -> np.ndarray:
    if frames_rgb.ndim != 4:
        raise ValueError(f"Expected frames T x H x W x C, got shape {frames_rgb.shape}")
    half = clip_frames // 2
    start = int(center_index) - half
    indices = [min(len(frames_rgb) - 1, max(0, start + offset)) for offset in range(clip_frames)]
    return frames_rgb[indices]


def build_slowfast_pathways(window_rgb: np.ndarray, alpha: int, crop_size: int):
    import torch

    if window_rgb.ndim != 4 or window_rgb.shape[-1] != 3:
        raise ValueError(f"Expected RGB window T x H x W x 3, got shape {window_rgb.shape}")
    resized = [
        cv2.resize(frame, (crop_size, crop_size), interpolation=cv2.INTER_AREA)
        for frame in window_rgb
    ]
    array = np.stack(resized, axis=0).astype(np.float32) / 255.0
    array = (array - SLOWFAST_MEAN) / SLOWFAST_STD
    fast_pathway = torch.from_numpy(array).permute(3, 0, 1, 2).contiguous()
    slow_indices = torch.linspace(0, fast_pathway.shape[1] - 1, fast_pathway.shape[1] // alpha).long()
    slow_pathway = torch.index_select(fast_pathway, 1, slow_indices)
    return [slow_pathway, fast_pathway]


def flatten_slowfast_feature(feature) -> np.ndarray:
    feature = feature.detach().float().cpu()
    if feature.ndim == 5 and feature.shape[-1] == 2304:
        feature = feature.mean(dim=(1, 2, 3))
    elif feature.ndim >= 2 and feature.shape[1] == 2304:
        if feature.ndim > 2:
            feature = feature.mean(dim=tuple(range(2, feature.ndim)))
    elif feature.ndim > 2:
        feature = feature.reshape(feature.shape[0], -1)
    feature = feature.reshape(feature.shape[0], -1)
    vector = feature[0].numpy().astype(np.float32)
    if vector.shape[0] != 2304:
        raise RuntimeError(f"Expected SlowFast feature dim 2304, got {vector.shape[0]}")
    return vector


def sample_frame_indices(frame_count: int, source_fps: float, sample_fps: float, max_frames: int) -> list[int]:
    if frame_count <= 0:
        return []
    if source_fps <= 0:
        raise ValueError("source_fps must be positive")
    if sample_fps <= 0:
        raise ValueError("sample_fps must be positive")
    if max_frames <= 0:
        raise ValueError("max_frames must be positive")

    step = max(1, int(round(source_fps / sample_fps)))
    indices = list(range(0, frame_count, step))
    if not indices:
        indices = [0]
    if len(indices) > max_frames:
        positions = np.linspace(0, len(indices) - 1, num=max_frames)
        indices = [indices[int(round(pos))] for pos in positions]
    return sorted(set(min(frame_count - 1, max(0, int(index))) for index in indices))


def read_clip_rows(path: Path, offset: int, limit: int | None) -> list[dict[str, str]]:
    rows: list[dict[str, str]] = []
    with path.open("r", encoding="utf-8", newline="") as file:
        reader = csv.DictReader(file)
        for index, row in enumerate(reader):
            if row.get("status") not in {"sliced", "exists"}:
                continue
            if index < offset:
                continue
            rows.append(row)
            if limit is not None and len(rows) >= limit:
                break
    return rows


def make_record(
    row: dict[str, str],
    feature_path: Path,
    status: str,
    backend: str,
    shape: list[int],
    source_fps: float,
    duration_seconds: float,
    feature_fps: float,
    error: str = "",
) -> FeatureRecord:
    return FeatureRecord(
        clip_id=row.get("clip_id", ""),
        video_id=row.get("video_id", ""),
        action_id=row.get("action_id", ""),
        clip_path=row.get("clip_path", ""),
        feature_path=str(feature_path),
        status=status,
        backend=backend,
        num_frames=int(shape[0]) if shape else 0,
        source_fps=round(float(source_fps), 4),
        duration_seconds=round(float(duration_seconds), 4),
        feature_fps=round(float(feature_fps), 4),
        feature_shape=[int(value) for value in shape],
        error=error,
    )


def build_summary(records: list[FeatureRecord]) -> dict[str, object]:
    status_counts: dict[str, int] = {}
    for record in records:
        status_counts[record.status] = status_counts.get(record.status, 0) + 1
    feature_dims = sorted({record.feature_shape[1] for record in records if len(record.feature_shape) == 2})
    total_frames = sum(record.num_frames for record in records if record.status in {"extracted", "exists"})
    return {
        "total": len(records),
        "status_counts": status_counts,
        "feature_dims": feature_dims,
        "total_feature_frames": total_frames,
        "backend": records[0].backend if records else "",
    }


def build_feature_manifest(records: list[FeatureRecord]) -> dict[str, object]:
    backend = records[0].backend if records else ""
    note = (
        "cv2-smoke features are for pipeline smoke tests only, not model training."
        if backend == "cv2-smoke"
        else "SlowFast R50 pooled features for ActionFormer training/inference."
    )
    return {
        "version": "1.0",
        "feature_key": "feats",
        "feature_layout": "T x C",
        "note": note,
        "database": {
            record.clip_id: {
                "video_id": record.video_id,
                "action_id": record.action_id,
                "clip_path": record.clip_path,
                "feature_path": record.feature_path,
                "backend": record.backend,
                "source_fps": record.source_fps,
                "duration_seconds": record.duration_seconds,
                "feature_fps": record.feature_fps,
                "feature_shape": record.feature_shape,
            }
            for record in records
            if record.status in {"extracted", "exists"}
        },
    }


if __name__ == "__main__":
    main()
